Update auto-bicep.yml

diff --git a/.github/workflows/auto-bicep.yml b/.github/workflows/auto-bicep.yml
--- a/.github/workflows/auto-bicep.yml
+++ b/.github/workflows/auto-bicep.yml
@@ -23,17 +23,14 @@ jobs:
         with:
           # Specify the script here
           inlineScript: |
-            git status
             # Get path of last file checked in
-            pwd
             cd $GITHUB_WORKSPACE
-            pwd
             LAST_PATH=$( git log --pretty="" --name-only -n 100 origin/master... -- | fgrep -v ".github" | head -1 )
-            echo Last file modified: $LAST_PATH
+            echo $LAST_PATH: Last file modified.
 
             # Look for the main template file in this file's path or parents
             SAMPLEFOLDER_PATH=$( dirname "$LAST_PATH" )
-            echo Last folder modified: $SAMPLEFOLDER_PATH
+            echo $SAMPLEFOLDER_PATH: Last folder modified
 
             TESTFOLDER_PATH=$SAMPLEFOLDER_PATH
             FOUNDFOLDER_PATH=
@@ -43,20 +40,19 @@ jobs:
               MAINBICEP_PATH=$TESTFOLDER_PATH/main.bicep
               AZDEPLOYJSON_PATH=$TESTFOLDER_PATH/azuredeploy.json
 
-              echo "SAMPLEFOLDER_PATH=$FOUNDFOLDER_PATH" >> $GITHUB_ENV
-              echo "MAINBICEP_PATH=$MAINBICEP_PATH" >> $GITHUB_ENV
-              echo "AZDEPLOYJSON_PATH=$AZDEPLOYJSON_PATH" >> $GITHUB_ENV
+              if [ -f $MAINBICEP_PATH ]; then
+                FOUNDFOLDER_PATH=$TESTFOLDER_PATH
+                echo Found main template in $FOUNDFOLDER_PATH
 
-              if [ -f $MAINBICEP_PATH ]; then          
                 echo Running: az bicep build --file $MAINBICEP_PATH --outfile $AZDEPLOYJSON_PATH
                 az bicep build --file $MAINBICEP_PATH --outfile $AZDEPLOYJSON_PATH
               fi
 
-              TESTFOLDER_PATH=$( dirname "$TESTFOLDER_PATH" )
+              TESTFOLDER_PATH=$SAMPLEFOLDER_PATH
             done
 
             if [ ! $FOUNDFOLDER_PATH ]; then
-                echo "Could not find main.bicep or azdeploy.json in folder or parents of $SAMPLEFOLDER_PATH" 1>&2
+                echo "Could not find main.bicep or azdeploy.json in folders." 1>&2
                 exit 1
             fi          
 
